# Tensors in PyTorch and their connection to Numpy

In [1]:
import numpy as np
import torch

In [14]:
x = torch.rand(3,2)
y = torch.ones(x.size())
z = x+y
z

tensor([[1.7538, 1.6031],
        [1.8255, 1.8452],
        [1.5943, 1.3273]])

## We can use indexing and slices with PyTorch

In [19]:
z[:,1]

tensor([1.6031, 1.8452, 1.3273])

## In PyTorch we have 2 types of methods:
- in place == add(2)
- copy == add_(2)

In [21]:
# Copy
z.add(4)

tensor([[5.7538, 5.6031],
        [5.8255, 5.8452],
        [5.5943, 5.3273]])

In [22]:
z

tensor([[1.7538, 1.6031],
        [1.8255, 1.8452],
        [1.5943, 1.3273]])

In [24]:
# In place
z.add_(4)

tensor([[5.7538, 5.6031],
        [5.8255, 5.8452],
        [5.5943, 5.3273]])

In [25]:
z

tensor([[5.7538, 5.6031],
        [5.8255, 5.8452],
        [5.5943, 5.3273]])

## Reshaping

In [26]:
z.size()

torch.Size([3, 2])

In [27]:
z.resize_(2,3)

tensor([[5.7538, 5.6031, 5.8255],
        [5.8452, 5.5943, 5.3273]])

## Numpy to Torch and Torch to Numpy

In [50]:
a = np.random.rand(4,3)
a

array([[0.3634922 , 0.49339388, 0.13472708],
       [0.12728128, 0.93587516, 0.87464616],
       [0.56567351, 0.70077489, 0.98366669],
       [0.44984973, 0.99479875, 0.93523262]])

In [51]:
# Change Numpy array to Torch tensor
b = torch.from_numpy(a)
type(b)

torch.Tensor

In [52]:
# Change Torch tensor to Numpy array
c = b.numpy()
c

array([[0.3634922 , 0.49339388, 0.13472708],
       [0.12728128, 0.93587516, 0.87464616],
       [0.56567351, 0.70077489, 0.98366669],
       [0.44984973, 0.99479875, 0.93523262]])

#### The memory is shared between Numpy array and Torch tensors. For example:

In [53]:
b.mul_(2)
b

tensor([[0.7270, 0.9868, 0.2695],
        [0.2546, 1.8718, 1.7493],
        [1.1313, 1.4015, 1.9673],
        [0.8997, 1.9896, 1.8705]], dtype=torch.float64)

In [54]:
a

array([[0.7269844 , 0.98678777, 0.26945415],
       [0.25456256, 1.87175033, 1.74929232],
       [1.13134702, 1.40154978, 1.96733338],
       [0.89969946, 1.9895975 , 1.87046524]])

In [55]:
c

array([[0.7269844 , 0.98678777, 0.26945415],
       [0.25456256, 1.87175033, 1.74929232],
       [1.13134702, 1.40154978, 1.96733338],
       [0.89969946, 1.9895975 , 1.87046524]])